//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomapperExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSkill
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public string Skillname { get; set; }
        public string rating { get; set; }
    }
}
